---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
# SSViewer:
#   theme: 'simple'
SSViewer:
   theme: 'playground'
#
#SSViewer:
#  theme: 'skeleton-framework-playground'
